/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integradora_1;

import javax.swing.JOptionPane;

/**
 *
 * @author Yair
 */
public class Integradora1 extends javax.swing.JFrame {

    /**
     * Creates new form Integradora1
     */
    public Integradora1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb1 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jpresente = new javax.swing.JRadioButton();
        jpasado = new javax.swing.JRadioButton();
        jfuturo = new javax.swing.JRadioButton();
        termin = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        corre = new javax.swing.JLabel();
        buenas = new javax.swing.JLabel();
        malas = new javax.swing.JLabel();
        buenas1 = new javax.swing.JLabel();
        buenas2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb1.setText("Mostrar");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar(evt);
            }
        });

        jpresente.setText("presente");
        jpresente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpresenteActionPerformed(evt);
            }
        });

        jpasado.setText("pasado");
        jpasado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasadoActionPerformed(evt);
            }
        });

        jfuturo.setText("Furturo");
        jfuturo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jfuturo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfuturoActionPerformed(evt);
            }
        });

        termin.setText("Terminar");
        termin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminActionPerformed(evt);
            }
        });

        corre.setBackground(new java.awt.Color(255, 255, 255));
        corre.setForeground(new java.awt.Color(153, 255, 153));
        corre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane1.setLayer(corre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buenas.setText("incorrectas");

        malas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buenas1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buenas2.setText("corectas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jb1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpasado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpresente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfuturo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(132, 132, 132)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buenas2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buenas1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buenas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(malas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                                .addComponent(termin)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb1)
                        .addGap(63, 63, 63)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpresente)
                        .addGap(18, 18, 18)
                        .addComponent(jpasado)))
                .addGap(18, 18, 18)
                .addComponent(jfuturo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buenas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buenas2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termin)
                    .addComponent(malas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buenas1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpresenteActionPerformed
        // TODO add your handling code here:here
        jpasado.setSelected(false);
        jfuturo.setSelected(false);
        valorOp = 0;
        verificarRespuesta();
    }//GEN-LAST:event_jpresenteActionPerformed

    private void jpasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasadoActionPerformed
        // TODO add your handling code here:
        jpresente.setSelected(false);
        jfuturo.setSelected(false);
        valorOp = 1;
        verificarRespuesta();
    }//GEN-LAST:event_jpasadoActionPerformed

    private void jfuturoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfuturoActionPerformed
        // TODO add your handling code here:
        jpasado.setSelected(false);
        jpresente.setSelected(false);
        valorOp = 2;
        verificarRespuesta();
    }//GEN-LAST:event_jfuturoActionPerformed

    private void mostrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar
        // TODO add your handling code here:
        arreglos();


    }//GEN-LAST:event_mostrar

    private void terminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Numero de acierto: "+ conteo+
                "\nNumero de errores: "+ conteoM,"puntaje",JOptionPane.INFORMATION_MESSAGE);
       
        
        System.exit(0);

    }//GEN-LAST:event_terminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integradora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integradora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integradora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integradora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integradora1().setVisible(true);
            }
        });
    }
    int aleatorio1, aleatorio2;
    int valorOp;
    int conteo = 0;
    int conteoM = 0;
    
    public void aleatorios(){
      aleatorio1 = (int) (Math.random() * 10);
        aleatorio2 = (int) (Math.random() * 3);
    }

    public void arreglos() {
        String verbo, tiempo;
        String verbos[] = {"Transformar", "Cambiar", "Explicar", "Dibujar", "Enseñar", "Separar", "Considerar", "Identificar", "Analizar", "Crear"};
        String conjugacion[] = {"Presente", "Pasado", "Futuro"};
        aleatorios();
        verbo = verbos[aleatorio1];
        tiempo = conjugacion[aleatorio2];
        jlb1.setText("Conjuga el verbo: " + verbo + " en " + tiempo);
        verboconjugado(verbo, tiempo);

    }

    private void verboconjugado(String verbo, String tiempo) {
        if (verbo.equals("Transformar")) {
            jpresente.setText("Transformo");
            jpasado.setText("Transforme");
            jfuturo.setText("Transformare");
        }
        if (verbo.equals("Cambiar")) {
            jpresente.setText("Cambio");
            jpasado.setText("Cambie");
            jfuturo.setText("Cambiare");
        }
        if (verbo.equals("Explicar")) {
            jpresente.setText("Explico");
            jpasado.setText("Explique");
            jfuturo.setText("Explicare");
        }
        if (verbo.equals("Dibujar")) {
            jpresente.setText("Dibujo");
            jpasado.setText("Dibuje");
            jfuturo.setText("Dibujare");
        }
        if (verbo.equals("Enseñar")) {
            jpresente.setText("Enseño");
            jpasado.setText("Enseñe");
            jfuturo.setText("Enseñare");
        }
        if (verbo.equals("Separar")) {
            jpresente.setText("Separo");
            jpasado.setText("Separe");
            jfuturo.setText("Separare");
        }
        if (verbo.equals("Considerar")) {
            jpresente.setText("Considero");
            jpasado.setText("Considere");
            jfuturo.setText("Considerare");
        }
        if (verbo.equals("Identificar")) {
            jpresente.setText("Identifico");
            jpasado.setText("Identifique");
            jfuturo.setText("Identificare");
        }
        if (verbo.equals("Analizar")) {
            jpresente.setText("Analizo");
            jpasado.setText("Analize");
            jfuturo.setText("Analizare");
        }
        if (verbo.equals("Crear")) {
            jpresente.setText("Creo");
            jpasado.setText("Cree");
            jfuturo.setText("Creare");
        }

    }

    private void verificarRespuesta() {

        if (valorOp == aleatorio2) {
            corre.setText("correcto");
            conteo(1);

        } else {
            corre.setText("incorrecto");
            conteo(2);
        }
        
//        para limpiar botones            
//        jpasado.setSelected(false);
//        jfuturo.setSelected(false);
//        jpresente.setSelected(false);
        
    }

    private void conteo(int respuesta) {
        if (respuesta == 1) {
            conteo++;
            String conteoS = String.valueOf(conteo);
            buenas1.setText(conteoS);
        } else {
            conteoM++;
            String conteoSM = String.valueOf(conteoM);
            malas.setText(conteoSM);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buenas;
    private javax.swing.JLabel buenas1;
    private javax.swing.JLabel buenas2;
    private javax.swing.JLabel corre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jb1;
    private javax.swing.JRadioButton jfuturo;
    private javax.swing.JLabel jlb1;
    private javax.swing.JRadioButton jpasado;
    private javax.swing.JRadioButton jpresente;
    private javax.swing.JLabel malas;
    private javax.swing.JButton termin;
    // End of variables declaration//GEN-END:variables
}
